"""bugfix: review model rating col

Revision ID: d377352aa58d
Revises: 607546123fc0
Create Date: 2023-05-25 11:18:10.864347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd377352aa58d'
down_revision = '607546123fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
